language: node_js
node_js:
  - '10'
install:
  - npm ci
script:
  - npm run lint
  - npm run build
deploy:
  provider: npm
  email: me@chregu.tv
  skip_cleanup: true
  api_key:
    secure: "uRv5x0GB5oKy/3VeF2/mv2vb1QD5IWzaH78Er1RRQwa1P9n8OttFsNrhG9ZKF8o6ukjaEnGbzuAP63KfyW+kpFKBNblLk8aI86ZWxK43wa1un2gKobbceyyEzAibsiVNSWdEkN0xfbR6XXK/hmigbUiCw9nPiAuZpwv6D5PjL/du4GMtJSuRcgBL2sE0gSDMPVfGwn04OpApgteWSolFWbnngl5GtJQINVWiJWSzm1++iFSnrS7XYDAwY1U3vkrF+zMisR9USu2ZZ9A9eoJJI6pQVvM7j3o8TyrNSTm9x8UUd92192ide0vjbFi1V4WEAbKWpeNEq8yZXfd9yLt3I2rknvLqw4yPXI7Na1XJgUOKw+f/02zkqjsD7LKvFj3z5tBTtrL9Y2yE3Te3TeTguZ/IYg6KDZ3aqHZuTHNH4CSE4BEat2diveBNMLn1q3NbHAZhuktT6g4IcZMt43iCzl1kLmd3iTA15CNNHmxslcwV1JLgVUzvu14Y4kne/dWS2ticyj/Dg/7p0Mjjk95L4dxECqJgqkX//Wq2/CzHkcLFRosh4vASoCa2soM2KPDEK46XQBLyTHLNL4F1TMArlYB07pgIQcDOX7muLgbDXronWQTtDMb/iPkYDkm1mdGjpaYUVcCZ7mqkKJNO/tlIrGE/Nfwbw9l+61S51Yszzao="
  on:
    all_branches: true
    tags: true
branches:
  only:
  - master
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/
