language: node_js
node_js:
- '10'
install:
- npm ci
script:
- npm run lint
- npm run build
deploy:
  provider: npm
  email: me@chregu.tv
  skip_cleanup: true
  api_key:
    secure: UIhZsu4BqbAFegcfjzSO/drkHzBzyjbWJOkuw6rOxIOE3P/ZfiTUiXo7BonVVa7uRvfp+jhSf5gTONK1yh+dtCSiRYbOBQaMpuwc83qPUlF1ZfKkTwGLEvxXowXUw5l9Pq2e8k5rxghLhDnTbjUhQTY+os+hUXz8pIwN04Mnk1Z0wgn0wn92+SUjo74hH1+tXPGsj47UliV0qWMtmAG6+QTFoRnab9jOF+pNPqLiZ6prLFoss3AiIJIaFAAbIU+hZyvCRAOTuzw27QatDKU5JYSXFCNJNdgA+XEEcBXY7MN+n6zU0fomraLAlKwNZVZ1lF5wKmWFj/YmK4qUbjwilJoop5YjO6DbfmeLukirps1WFCL1ZygCqBBEpkaiIoJbVdP7XrNz+E3PzWC67j+A1m1YWSVeoAXviQH1N+U3SDvIMGUr+VA41DIXVxbfrFLd7R7r+5WGI+gkoaxTJ8BJDPI3esrSKoUfszNFGg350bC4qv3u2KvuDY6/RdgUd9v6hQUOVHKeDtWj0jjwN2g15ukjd75tGahtnNBvEP+QvcmAoJnT/ZhcSJKZQhVg0vH8fiBAOOfFXDelqSaa9SOAgJQp+8xel4bvg9QriZn9TaXXVqS8xVnBJ1RyWWknKWnrfrclDWYGDUPPLz/jM5SVZiAqoYHKWQMcN2fhp1ubPHk=
  on:
    all_branches: true
    tags: true
branches:
  only:
  - master
  - "/^v[0-9]+\\.[0-9]+\\.[0-9]+$/"
